// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATaSETlqR9r0ttyjufSrAFCDWOzmBMuj4',
    appId: '1:202436305401:web:cf95f8166b588f566c9d28',
    messagingSenderId: '202436305401',
    projectId: 'maktab-kutubxonasi',
    authDomain: 'maktab-kutubxonasi.firebaseapp.com',
    storageBucket: 'maktab-kutubxonasi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTbWjz4KyXcdBgvc_iVaTRs75lLuiMdg',
    appId: '1:278200026150:android:5fab955070816b22df12e7',
    messagingSenderId: '278200026150',
    projectId: 'flutter-contest-31e5c',
    storageBucket: 'flutter-contest-31e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeTOf3Edcra3eRtQMF2zBiL25cwaaVoo',
    appId: '1:278200026150:ios:ba9f27966dcd00cddf12e7',
    messagingSenderId: '278200026150',
    projectId: 'flutter-contest-31e5c',
    storageBucket: 'flutter-contest-31e5c.appspot.com',
    iosBundleId: 'com.mozz.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTeTOf3Edcra3eRtQMF2zBiL25cwaaVoo',
    appId: '1:278200026150:ios:ba9f27966dcd00cddf12e7',
    messagingSenderId: '278200026150',
    projectId: 'flutter-contest-31e5c',
    storageBucket: 'flutter-contest-31e5c.appspot.com',
    iosBundleId: 'com.mozz.chat',
  );
}
